<a href="https://colab.research.google.com/github/mwahajkhan/Python-For-Data-Engineering/blob/main/Array_Creation_and_Attributes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

nums = [1, 2, 3, 4, 5]

array1= np.array(nums)
print(array1)

[1 2 3 4 5]


In [4]:
zero_array = np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [3]:
one_array = np.ones(3)
print(one_array)

[1. 1. 1.]


In [6]:
range_array = np.arange(1, 10, 2)
print(range_array)

[1 3 5 7 9]


In [11]:
random_array = np.random.randint(1, 100, 5)
print(random_array)

[54 97 29 35 11]


In [15]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.6918337  0.10733755 0.92439194]
 [0.24723785 0.76042825 0.98136983]
 [0.74100133 0.19903656 0.2462912 ]]


In [16]:
shape = range_array.shape
print(shape)

(5,)


In [17]:
size = range_array.size
print(size)

5


In [18]:
dtype = range_array.dtype
print(dtype)

int64


In [20]:
print(range_array.ndim)

1
