<a href="https://colab.research.google.com/github/mwahajkhan/Python-For-Data-Engineering/blob/main/Indexing_and_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

array1 = np.array([10, 20, 30, 40, 50])

secondelement = array1[1]

print(secondelement)

20


In [3]:
print(array1[-2])

40


In [4]:
sliced_arr = array1[1:4]
print(sliced_arr)

[20 30 40]


In [5]:
step_arr = array1[::2]
print(step_arr)

[10 30 50]


In [32]:

#np.random.rand(1, 3, 3)
matrix_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


element = matrix_arr[1,1]
print(element)


5


In [35]:
second_row = matrix_arr[1,:]
print(second_row)

[4 5 6]


In [37]:
second_col = matrix_arr[:,1]
print(second_col)

[2 5 8]


In [38]:
data = np.array([1, 2, 3, np.nan, 4, 5])

missing = np.isnan(data)
print(missing)

[False False False  True False False]


In [39]:
data_fill = np.nan_to_num(data, nan=100)
print(data_fill)

[  1.   2.   3. 100.   4.   5.]
