<a href="https://colab.research.google.com/github/mwahajkhan/Python-For-Data-Engineering/blob/main/Linear_Algebra_and_Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

mul = np.dot(array1, array2)

print(mul)

[[19 22]
 [43 50]]


In [4]:
invr = np.linalg.inv(array1)
print(invr)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
eval, evect = np.linalg.eig(array1)

print(eval)
print(evect)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [7]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)

print(mean)
print(std_dev)

3.0
1.4142135623730951


In [8]:
data2 = np.array([11, 12, 13, 14, 15])

cor = np.corrcoef(data, data2)
print(cor)

[[1. 1.]
 [1. 1.]]


In [11]:
np.savetxt('output.csv', mul, delimiter=',')

In [12]:
np.save('output.npy', mul)
new_matrix = np.load('output.npy')

In [19]:
import pandas as pd

df = pd.DataFrame(mul)
df.to_excel('output.xlsx')